name: BEAR.Sunday
safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
pygments: true
